### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by ghost** [gomint/gomint#247]
This is not an issue but a request. Close if `not` allowed.

`getContents()` - get the content of a player's inventory [link](https://github.com/NukkitX/Nukkit/blob/05edfbf4efc1da8b1698df8a599ea456ef2ca030/src/main/java/cn/nukkit/inventory/Inventory.java#L42)

`dispatchCommand()` - runs command from the console (Pretty sure there's an issue created for this [link](https://github.com/NukkitX/Nukkit/blob/05edfbf4efc1da8b1698df8a599ea456ef2ca030/src/main/java/cn/nukkit/Server.java#L679))

`setSpawnLocation()` - sets a world's spawn location [link](https://github.com/NukkitX/Nukkit/blob/05edfbf4efc1da8b1698df8a599ea456ef2ca030/src/main/java/cn/nukkit/level/Level.java#L2449))

there are more features we need for GoMint but..I don't want to waste my time writing hundreds of words and this just get closed down.

**Comment by Janmm14** [comment]
### About `getContents()`:

Clearly seeing the improvement, atm you can iterate from `0` to `size()` and use `getItem(int)`.

### About `dispatchCommand()`:

Atm there is no framework that allows non-player command execution.
I suggest instead of attempting to console commands for inter-plugin-communication that plugins expose an API.

(I don't know whether its planned to add this or not)

### About `setSpawnLocation()`:

Workaround: Use PlayerJoinEvent and PlayerRespawnEvent

**Comment by ghost** [comment]
With the `About setSpawnLocation(): Workaround: Use PlayerJoinEvent and PlayerRespawnEvent`, I've tried that before and I got chunk bug. (I simply teleported the player to a coordinates where I want the spawn location to be)

**Comment by Janmm14** [comment]
Respawn already allows you to set the respawn point, so your issue is with teleportation on join? Might be worth a separate issue as teleports should never cause (such) issues.

**Comment by ghost** [comment]
I realized GoMint doesn't save players' data too.
