### ISSUE TITLE
Nametags können nicht geändert werden.

### ISSUE THREAD

**Issue by KCodeYT** [gomint/gomint#283]
Nach einem EntityPlayer#setNameTag(text); wird der Nametag von dem Spieler nicht geändert.

Getestet auf: localhost
Entity 1: Laptop (Win 10, 1.5.0)
Entity 2: Handy (Android 8, 1.5.0.14)

**Comment by geNAZt** [comment]
Issue template?

**Comment by Goodstuff4UonYT** [comment]
@geNAZt Here:
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior



## Current Behavior



## Possible Solution



## Steps to Reproduce (for bugs)


1.
2.
3.
4.

## Context



## Your Environment

* Version used:
* Client version and OS:
* Operating System and version / java version of the server:
* Link to the logs:

**Comment by Janmm14** [comment]
@Goodstuff4UonYT he doesn't want an empty issue template of course...

**Comment by Goodstuff4UonYT** [comment]
@Janmm14 He asked for an "Issue template?"^^

**Comment by b348** [comment]
@Janmm14 Facepalm...
