### ISSUE TITLE
Pass "CommandOutput" object to "execute" method

### ISSUE THREAD

**Issue by volcanopowder** [gomint/gomint#592]
**Is your feature request related to a problem? Please describe.**
There is not a problem associated with this change, though I think it would streamline the command processing for plugin developers. I do not see the use of having the ```CommandOutput``` created and returned by the plugin developer, and it could be created as a single object by the event handler in the server and then passed from ```Command``` to ```Command``` and chaining instead of a new object being created each time.

The reason I think this is an important change is because it would prevent output from becoming muddled from multiple handlers handling the same command execution. For example, if a plugin were to implement a command ```a``` and another plugin were to implement the same command with different output, their outputs would not be muddled or overridden and it would be the last successfully executed handler (i.e. the handler that returns ```true```) that would emit the message.

**Describe the solution you'd like**
1. A ```CommandOutput``` being created prior to the handling of a command being executed
2. The method ```execute``` being changed to ```execute(CommandSender sender, String alias, Map<String, Object> parameters, CommandOutput output)```
3. The return type of ```execute``` to ```boolean``` of whether or not the command execute successfully.

**Comment by geNAZt** [comment]
There is no command chaining in GoMint (at least not intended). If two plugins collide on the command name `a` the earlier loaded one gets moved to `pluginname:a` while the other one takes over ownership of `a`. See https://github.com/gomint/GoMint/blob/master/gomint-server/src/main/java/io/gomint/server/command/CommandManager.java#L327 for that behaviour. Since there is currently no way that two command handler execute on `a` i don't see why a passed `CommandOutput` would benefit the developer. 

Currently the behaviour of `CommandOutput` is not completed either. It only supports already correct sentences but my plan for `CommandOutput` is that it can use the i18n system directly. So once the i18n integration has been done plugins could use their resources to load languages and refer to them by key `success("item.given", item.getName())` for example. Since the usage of that example depends on the plugin instance giving the `CommandOutput` a generic one would not work without storing which message came from which plugin.
