### ISSUE TITLE
[a5ebb3] GoMint: io.gomint.server.network.PlayerConnection.sendWorldInitialization, io.gomint.server.entity.EntityPlayer.prep...

### ISSUE THREAD

**Issue by GoMinty** [gomint/gomint#736]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><b><a href="https://gomint.sp.backtrace.io/dashboard/gomint/project/GoMint/group/a5ebb34c2327d4ccb11e7eea9bb43f5774cef1219bcd8e82557b3d1e4c657b6a">New error: [GoMint]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>GoMint</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>s:32c8d1d5</code> &mdash; 1</li></ul><br>
<strong>tag.plugin.crash</strong> &mdash; 1
        <ul>
                <li><code>1</code> &mdash; 1</li></ul><br>
<strong>plugin</strong> &mdash; 1
        <ul>
                <li><code>Portal v1.0</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>java.lang.NullPointerException</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
io.gomint.server.network.PlayerConnection.sendWorldInitialization
io.gomint.server.entity.EntityPlayer.prepareEntity
io.gomint.server.network.handler.PacketResourcePackResponseHandler.switchToLogin
io.gomint.server.network.handler.PacketResourcePackResponseHandler.handle
io.gomint.server.network.PlayerConnection.handlePacket
io.gomint.server.network.PlayerConnection.handleBufferData
io.gomint.server.network.PlayerConnection.handleSocketData
io.gomint.server.network.PlayerConnection.updateNetwork
io.gomint.server.network.PlayerConnection.update
io.gomint.server.network.NetworkManager.update
io.gomint.server.GoMintServer.startAfterRegistryInit
io.gomint.server.Bootstrap.bootstrap
io.gomint.server.Bootstrap.main</code>
        </td>
    </tr></table>

**Comment by geNAZt** [comment]
Invalid biome ID failure, need to check where those biome ID comes from

**Comment by vojtech-stehlik** [comment]
![obrazek](https://user-images.githubusercontent.com/40556088/107396164-cf2c7700-6afd-11eb-89b7-2f7d01a20fa8.png)
console

**Comment by fl3x1324** [comment]
It comes from here: when a player joins for the first time the spawnLocation for the player is null in this piece of code: `io.gomint.server.network.PlayerConnection#sendWorldInitialization`, so the world spawn is used.
 In my case the problem is that the world spawn is `150, 75, 150`. When calling `world.getBiome(position)` in `io.gomint.server.world.WorldAdapter#getBiome` the block coordinates are converted to chunk ones, resulting in `9, 9` for chunk x and chunk z. Then after the chunk is created with the chunk coordinates and `generate=true`, when getting the biome with `chunk.biome(150 & 15, 150 & 15)` we end up with `chunk.biome(6, 6)`. In that method the biome ID is generated by shifting 6 four times to the left and adding 6 to it, both x and z are 6. The result is `96 + 6 = 102`. When calling `getByte` on `this.biomes` in `ChunkAdapter` the ID turns out to be 119. There's no biome with such ID in the `Biomes` enum.
